services:
  - type: web
    name: cinta-verde
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_APP_SUPABASE_URL
        sync: false
      - key: VITE_APP_SUPABASE_ANON_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
